# name of your application
APPLICATION = SPG30-sensor-example

# platform for which the application will be built
PLATFORM ?= octa

# use the SBSFU bootloader
BOOTLOADER ?= 0
SHIELDS += SPG30
SPG30_CONNECTOR = 1


# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core