# name of your application
APPLICATION = no-scheduler-example

# platform for which the application will be built
PLATFORM ?= octa

# use the SBSFU bootloader
BOOTLOADER ?= 0
SHIELDS += Murata
MURATA_CONNECTOR = 3
LORAWAN_APPLICATION = iowttn

# Path to the octa-stack base directory:
STACKBASE ?= ../..

# Set PRINT_FLOATS to 1 to enable linker flags enabling float printf & sprintf
PRINT_FLOATS = 1

include $(STACKBASE)/core/Makefile.core