# name of your application
APPLICATION = murata-dualstack-example-ns

# platform for which the application will be built
PLATFORM ?= octa

PRINT_FLOATS = 1
# Add shields used in application
# Murata
SHIELDS += Murata-dualstack
MURATA_CONNECTOR = 1
LORAWAN_APPLICATION = devicedatabase

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core